name: Build APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kódu
      uses: actions/checkout@v4

    - name: Nastavenie Java (JDK 17)
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Vygeneruj chýbajúci Gradle Wrapper
      run: gradle wrapper

    - name: Povolenie spustenia gradlew
      run: chmod +x gradlew

    - name: Build s Gradle (Vytvorenie APK)
      run: ./gradlew assembleDebug

    - name: Uloženie hotového APK (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: meniny-app
        path: app/build/outputs/apk/debug/app-debug.apk
